
// script.js — adaptive schema + horizontal bars for long labels
const FILE_PATH = 'data.xlsx';
function shortenLabel(s, max=28){ s = String(s||''); return s.length>max ? s.slice(0,max-1)+'…' : s; }
function el(id){ return document.getElementById(id); }
function normalize(x){ return (x===undefined||x===null) ? '' : String(x).trim(); }
const SCHEMAS = { survey:{ cols:{ municipio:'3) Município onde reside:', campus:'Campus de Atuação', funcao:'6) Função exercida no Projeto IntegraCAR:' }, bolsistaRule:(r,c)=>String(r[c.funcao]||'').toLowerCase().includes('orientador') }, titulo:{ cols:{ municipio:'NOME MUNICÍPIO', campus:null, funcao:'NOME AUTOR', tituloSituacao:'SITUAÇÃO TÍTULO' }, bolsistaRule:(r,c)=>!!(r[c.funcao]||'') } };
function detectSchema(rows){ const has=(c)=>rows.length&&rows[0]&&Object.prototype.hasOwnProperty.call(rows[0],c); if (has('NOME MUNICÍPIO')||has('NOME MUNICÍPIO ')) return {key:'titulo',def:SCHEMAS.titulo}; return {key:'survey',def:SCHEMAS.survey}; }
function groupCount(rows, keySelector){ const m=new Map(); rows.forEach(r=>{ const k=keySelector(r); if(k) m.set(k,(m.get(k)||0)+1); }); return Array.from(m,([key,value])=>({key,value})).sort((a,b)=>b.value-a.value); }
function plotBarAdaptive(divId, labels, values, title){ const div=el(divId); if(!div) return; const maxLen=Math.max(0,...labels.map(l=>String(l||'').length)); const many=labels.length>8; const long=maxLen>14||many; if(long){ const h=Math.max(320,Math.min(1100,26*labels.length+80)); Plotly.newPlot(div,[{y:labels,x:values,type:'bar',orientation:'h',text:labels.map(l=>shortenLabel(l)),textposition:'auto',hovertemplate:'%{y}: %{x}<extra></extra>',cliponaxis:false}],{title,height:h,margin:{t:30,l:Math.min(300,10*maxLen),r:10},xaxis:{automargin:true},yaxis:{automargin:true},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)'},{displayModeBar:false,responsive:true}); } else { Plotly.newPlot(div,[{x:labels,y:values,type:'bar',text:labels.map(l=>shortenLabel(l,18)),textposition:'auto',hovertemplate:'%{x}: %{y}<extra></extra>',cliponaxis:false}],{title,margin:{t:30,b:80},xaxis:{tickangle:-30,automargin:true},yaxis:{automargin:true},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)'},{displayModeBar:false,responsive:true}); } }
let ALL_ROWS=[], ACTIVE={}, SCHEMA_KEY='survey';
async function loadXLSX(){ const res=await fetch('data.xlsx'); if(!res.ok) throw new Error('Falha ao baixar data.xlsx'); const buf=await res.arrayBuffer(); const wb=XLSX.read(buf,{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; return XLSX.utils.sheet_to_json(ws,{defval:''}); }
function setupFilters(rows,defs){ const cols=defs.cols; const campus=document.getElementById('fCampus'); const muni=document.getElementById('fMunicipio'); const func=document.getElementById('fFuncao'); const fill=(sel,vals,all)=>{ if(!sel) return; const uniq=Array.from(new Set(vals.filter(Boolean).map(v=>normalize(v)))).sort(); sel.innerHTML=`<option value="">${all}</option>`+uniq.map(v=>`<option value="${v}">${v}</option>`).join(''); }; if(cols.campus&&rows[0]&&Object.prototype.hasOwnProperty.call(rows[0],cols.campus)){ fill(campus,rows.map(r=>r[cols.campus]),'Todos'); campus.parentElement.style.display=''; } else if(campus){ campus.parentElement.style.display='none'; } fill(muni,rows.map(r=>r[cols.municipio]),'Todos'); fill(func,rows.map(r=>r[cols.funcao]),defs===SCHEMAS.titulo?'Todos os autores':'Todas'); ['change'].forEach(evt=>{ campus&&campus.addEventListener(evt,refresh); muni&&muni.addEventListener(evt,refresh); func&&func.addEventListener(evt,refresh); }); document.getElementById('btnLimpar')?.addEventListener('click',()=>{ if(campus) campus.value=''; if(muni) muni.value=''; if(func) func.value=''; refresh(); }); }
function getFiltered(rows,defs){ const cols=defs.cols; const c=normalize(document.getElementById('fCampus')?.value); const m=normalize(document.getElementById('fMunicipio')?.value); const f=normalize(document.getElementById('fFuncao')?.value); return rows.filter(r=>{ const rc=cols.campus?normalize(r[cols.campus]):''; const rm=normalize(r[cols.municipio]); const rf=normalize(r[cols.funcao]); return (cols.campus?(c?rc===c:true):true)&&(m?rm===m:true)&&(f?rf===f:true); }); }
let table; function refresh(){ const defs=ACTIVE.def; const cols=defs.cols; const rows=getFiltered(ALL_ROWS,defs); const kpiTotal=document.getElementById('kpiTotal'); if(kpiTotal) { let v=0; const t0=performance.now(); const step=()=>{ const p=Math.min(1,(performance.now()-t0)/600); kpiTotal.textContent=Math.round(v+(rows.length-v)*p); if(p<1) requestAnimationFrame(step); }; requestAnimationFrame(step); } const kpiCampiWrap=document.getElementById('kpiCampi')?.closest('.kpi'); if(cols.campus&&rows[0]&&Object.prototype.hasOwnProperty.call(rows[0],cols.campus)){ document.getElementById('kpiCampi').textContent=new Set(rows.map(r=>normalize(r[cols.campus]))).size; if(kpiCampiWrap) kpiCampiWrap.style.display=''; } else { if(kpiCampiWrap) kpiCampiWrap.style.display='none'; } document.getElementById('kpiMunicipios').textContent=new Set(rows.map(r=>normalize(r[cols.municipio]))).size; const bolsistasVal = (ACTIVE.key==='titulo')? new Set(rows.map(r=>normalize(r[cols.funcao]))).size : rows.filter(r=> SCHEMAS.survey.bolsistaRule(r, cols)).length; document.getElementById('kpiOrientadores').textContent=bolsistasVal; const byMun=groupCount(rows, r=>normalize(r[cols.municipio])); plotBarAdaptive('chartMunicipio', byMun.map(x=>x.key), byMun.map(x=>x.value), (ACTIVE.key==='titulo'?'Registros por Município (Títulos)':'Registros por Município')); if (ACTIVE.key==='titulo'){ const byAutor=groupCount(rows, r=>normalize(r[cols.funcao])); plotBarAdaptive('chartCampus', byAutor.map(x=>x.key), byAutor.map(x=>x.value), 'Registros por Autor'); } else { const byCampus=groupCount(rows, r=>normalize(r[cols.campus])); plotBarAdaptive('chartCampus', byCampus.map(x=>x.key), byCampus.map(x=>x.value), 'Registros por Campus'); } if (document.getElementById('dataTable')){ if(!table){ table=$('#dataTable').DataTable({ data:rows, columns:Object.keys(rows[0]||{}).map(k=>({title:k,data:k})), dom:'Bfrtip', buttons:[{extend:'csvHtml5',title:'dados_car'}], pageLength:10 }); document.getElementById('btnDownloadCSV')?.addEventListener('click', ()=> table.button('.buttons-csv').trigger()); } else { table.clear(); table.rows.add(rows); table.draw(); } } }
async function main(){ let rows=await loadXLSX(); rows=rows.map(r=>{ if ('NOME MUNICÍPIO ' in r && !('NOME MUNICÍPIO' in r)) r['NOME MUNICÍPIO']=r['NOME MUNICÍPIO ']; return r; }); ACTIVE=detectSchema(rows); ALL_ROWS=rows; const leftPanelHdr=document.querySelector('.panel h2'); if(leftPanelHdr) leftPanelHdr.setAttribute('data-panel-left-title','1'); setupFilters(ALL_ROWS, ACTIVE.def); refresh(); }
if (document.readyState==='loading'){ document.addEventListener('DOMContentLoaded', main); } else { main(); }
